apiVersion: sources.knative.dev/v1
kind: ContainerSource
metadata:
  name: kamelet-source
spec:
  template:
    spec:
      containers:
        - image: quay.io/openshift-knative/kn-connector-source-star-wars:1.0-SNAPSHOT
          name: timer
          env:
            - name: CAMEL_KAMELET_STAR_WARS_SOURCE_RESOURCE
              value: "starships"
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: default
